apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-registration.fullname" . }}
  labels:
    {{- include "self-registration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "self-registration.selectorLabels" . | nindent 4 }}

{{- if .Values.auth.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-traefik-forward-auth
  labels:
    {{- include "self-registration.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-traefik-forward-auth
  ports:
  - port: {{ .Values.auth.service.port }}
    targetPort: http
    protocol: TCP
    name: http

{{- end }}
